name: vakil_0098
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  http: ^0.13.5
  encrypt: ^5.0.1
  flutter_spinkit: ^5.1.0
  package_info_plus: ^1.4.3+1
  dio: ^4.0.6
  awesome_dialog: ^3.0.2
  photo_view: ^0.14.0
  persian_number_utility: ^1.1.3
  pull_to_refresh: ^2.0.0
  persian_datetime_picker: ^2.5.0
  material_design_icons_flutter: ^5.0.6996
  flutter_keyboard_visibility: ^5.4.0
  dotted_line: ^3.1.0
  dotted_border: ^2.0.0+3
  wechat_assets_picker: ^8.1.2
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^10.2.0
  dropdown_search: ^4.0.0
  fluttertoast: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: iransans
      fonts:
        - asset: assets/fonts/iran_sans.ttf
    - family: HacenTunisia
